config/routes.rb
Rails.application.routes.draw do

    namespace :com, :path => nil do
      namespace :nbos, :path => nil do
        namespace :core, :path => nil do
           get "/" => "auth#login"
           match 'login' => "auth#login", as: 'login', via: [:get, :post]
           match 'sign_up' => "users#sign_up", as: 'sign_up', via: [:get, :post]
           get 'user_profile' => "users#show", as: 'user_profile'
           match 'users' => "users#edit", as: 'edit', via: [:get, :post]
           get 'dash_board' => "users#dash_board", as: 'dash_board'
           match 'change_password' => "auth#change_password", as: 'change_password', via: [:get, :post]
           match 'forgot_password' => "auth#forgot_password", as: 'forgot_password', via: [:get, :post]
           get 'logout' => "auth#logout", as: 'logout'
           get 'get_media' => "media#get_media", as: 'get_media'
           put 'update_media' => "media#update_media", as: 'update_media'
        end  
      end
    end

    namespace :com, :path => nil do
      namespace :nbos, :path => nil do
        namespace :social, :path => nil do
          get '/auth/:provider/callback' => "social#create"
        end  
      end
    end 
      
end

app/controllers/com/nbos/core/auth_controller.rb
# This controller is responsible for handling 
# user login ,logout, change_password & forgot_password
# requests with Wavelabes API Server

class Com::Nbos::Core::AuthController < ApplicationController
  
  before_action :has_token!, :except => [:login, :forgot_password]
  before_action :check_server_connection!, :only => [:login]

  def login
    @login = create_basic_login_model
    if request.post?
      api_response = getAuthApi.login(params[:wavelabs_client_api_client_api_data_models_login_api_model], @auth_token)
      if api_response[:status] == 200
        @member = api_response[:member]
        create_session(@member)
        redirect_to :com_nbos_core_dash_board
      else
        @login = api_response[:login]
        render :login
      end
    end
  end

  def change_password
    @login = create_basic_login_model
    if request.post?
      api_response = getAuthApi.change_password(params[:wavelabs_client_api_client_api_data_models_login_api_model], session[:auth_token])
      if api_response[:status] == 200 || api_response[:status] == 400
        @login = api_response[:login]
      else
        @login = api_response[:login]
      end
    end
  end

  def logout
    api_response = getAuthApi.logout(session[:auth_token])
    if api_response[:status] == 200
      flash[:notice] = api_response[:login].message
      clear_session
      redirect_to :com_nbos_core_login
    end
  end

  def forgot_password
    @login = create_basic_login_model
    if request.post?
      api_response = getAuthApi.forgot_password(params[:wavelabs_client_api_client_api_data_models_login_api_model], @auth_token)
      if api_response[:status] == 200
        flash[:notice] = api_response[:login].message + " To #{api_response[:login].email}"
        redirect_to :com_nbos_core_login
      else
        @login = api_response[:login]
        render :forgot_password
      end
    end  
  end

  def omniauth_failure
    flash[:notice] = params
    redirect_to :com_nbos_core_login
  end

end

app/controllers/com/nbos/core/media_controller.rb
# This controller is responsible for handling 
# user's get profile picture & upload profile picture
# requests with Wavelabes API Server. 
# This controller will store the uploaded picture into client side
# temporary directory "Rails.root/tmp". After successfull upload into
# Wavelabs Server client side temporary file will be deleted. 

class Com::Nbos::Core::MediaController < ApplicationController
  before_action :has_token!


  def get_media
  	api_response = getMediaApi.get_media(session[:member]["id"], "profile", session[:auth_token])
  	if api_response[:status] == 200
      @media = api_response[:media]
      @file_path = @media.mediaFileDetailsList[1].to_h["mediapath"]
    else
      flash.now[:notice] = api_response[:message].message
      @media = create_media_model(nil)		
    end		
  end
  
  def update_media

    temp_file_path = uploadFile(params[:wavelabs_client_api_client_api_data_models_media_api_model][:newMedia])
    
    api_response = getMediaApi.upload_media(temp_file_path.to_path, "profile", session[:auth_token], session[:member]["id"]) 
    
    if api_response[:status] == 200
      flash[:notice] = api_response[:media].message if api_response[:media].message.present?
      @media = api_response[:media]
      redirect_to :com_nbos_core_get_media
    else
      flash[:notice] = api_response[:message].message
      redirect_to :com_nbos_core_get_media    
    end 

  end

 private 
 
  def uploadFile(file_obj)
    path = Rails.root.join('tmp', file_obj.original_filename)
    File.open(path , 'wb') do |file|
      file.write(file_obj.read)
    end
    return path
  end 

end  

app/controllers/com/nbos/core/users_controller.rb
# This controller is responsible for handling 
# user's sign_up , dash_board, show & edit 
# requests with Wavelabes API Server

class Com::Nbos::Core::UsersController < ApplicationController

  before_action :has_token!, :except => [:sign_up]

  def sign_up
    @login = create_basic_login_model
   if request.post?
     api_response = getUsersApi.sign_up(params[:wavelabs_client_api_client_api_data_models_login_api_model], @auth_token)
      if api_response[:status] == 200
        @login = api_response[:member]
        create_session(@login)
        redirect_to :com_nbos_core_dash_board
      else 
        @login = api_response[:member]
        render :sign_up
      end
   end
  end

  def dash_board
    # Need to implement the dashboard page 
  end  

  def show
   if request.get? && params[:id].present? 
    user_show_params = params
    api_response = getUsersApi.show(user_show_params, session[:auth_token])
    if api_response[:status] == 200
      @member = api_response[:member]
    else
      #@member = api_response[:member]
      flash[:notice] = api_response[:member].message
    end
   else
     flash[:notice] = "There was a problem with the request or Server. Please logout & ogin again."
   end 
  end

  def edit
    if request.post?
      user_update_params = params[:wavelabs_client_api_client_api_data_models_member_api_model]
      api_response = getUsersApi.update(user_update_params, session[:auth_token])
      if api_response[:status] == 200
        flash.now[:notice] = "Your Profile has been updated successfully."
        @member = api_response[:member]
        update_session(@member)
        render :show
      elsif api_response[:status] == 400
        @member = api_response[:member]
        render :edit
      else
        @member = create_member_model({"member" => user_update_params}, true)  
        @member.message = api_response[:member].message
        render :edit
      end
    else
      @member = create_member_model({"member" => session[:member]},false)  
    end  
  end

end

app/views/com/nbos/core/users/dash_board.html.erb
<h1>Welcome to Wavelabs Rails Client API.</h1>

app/views/com/nbos/core/users/edit.html.erb
<% if (@member.present? && @member.message.present?) || flash[:notice] %>
    <%= render partial: "com/nbos/core/shared/alerts", locals: {obj: @member, notice: flash[:notice]} %>
<% end %>

<div class="container">    
    <div id="signupbox" style="margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
      <div class="panel panel-info">
        <div class="panel-heading">
          <div class="panel-title">Edit Profile</div>
          <div style="float:right; font-size: 85%; position: relative; top:-10px;">
            <%#= link_to "Sign In", com_nbos_core_login_path, style: "color: #fff " %>
          </div>
        </div>
        <div class="panel-body">
          <%= form_for(@member, url: com_nbos_core_edit_path, method: 'post', html: { role: "form", id: "signupForm", class: "form-horizontal" }) do |f| %>
            <%= f.hidden_field :id,  :value => "#{@member.id}"%>
            <div class="form-group">
              <label for="usd" class="col-md-3 control-label">Description</label>
              <div class="col-md-9">
                 <%= f.text_field :description, autofocus: true, class: "form-control", id: "username", title: "Please enter your username", placeholder: "Description"  %>
                <%= errors_for @member, :description %>
              </div>
            </div>
            <% if !is_a_social_member? %>
            <div class="form-group">
              <label for="email" class="col-md-3 control-label">Email</label>

              <div class="col-md-9">
                <%= f.email_field :email, class: "form-control", id: "email", title: "Please enter your email", placeholder: "example@gmail.com", required: true%>
                <%= errors_for @member, :email %>
              </div>
            </div>
            <% end %>
            <div class="form-group">
              <label for="firstName" class="col-md-3 control-label">First Name</label>

              <div class="col-md-9">
               <%= f.text_field :firstName, class: "form-control", id: "firstName", title: "Please enter your first name", placeholder: "Jhon", required: true%>
                <%= errors_for @member, :firstName %>
              </div>
            </div>
            <div class="form-group">
              <label for="lastname" class="col-md-3 control-label">Last Name</label>

              <div class="col-md-9">
                <%= f.text_field :lastName, class: "form-control", id: "lastName", title: "Please enter your last name", placeholder: "Smith", required: true%>
                <%= errors_for @member, :lastName %>
              </div>
            </div>

            <div class="form-group">
              <label for="lastname" class="col-md-3 control-label">Phone</label>

              <div class="col-md-9">
                <%= f.text_field :phone, class: "form-control", id: "phone", title: "Please enter your phone number", required: true%>
                <%= errors_for @member, :phone %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-md-offset-3 col-md-9">
               <%= f.submit  "Save", class: "btn btn-success" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/com/nbos/core/users/show.html.erb
<% if (@member.present? && @member.message.present?) || flash[:notice] %>
    <%= render partial: "com/nbos/core/shared/alerts", locals: {obj: @member, notice: flash[:notice]} %>
 <% end %>

<% if @member.present? %>
<div class="container">    
    <div id="signupbox" style="margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
      <div class="panel panel-info">
        <div class="panel-heading">
          <div class="panel-title">Your Profile</div>
        </div>
        <div class="panel-body">
            <div class="table">
               <table class="showProfileTable">
                 <tr>
                    <td>Description</td>
                    <td><%= @member.description %></td>
                 </tr>
                 <tr>
                    <td>Email</td>
                    <td><%= @member.email %></td>
                 </tr>
                 <tr>
                    <td>Firs Name</td>
                    <td><%= @member.firstName %></td>
                 </tr>
                 <tr>
                    <td>Last Name</td>
                    <td><%= @member.lastName %></td>
                  </tr>
                  <tr>
                    <td>Phone</td>
                    <td><%= @member.phone %></td>
                  </tr>
                  <% if @member.social_accounts.size > 0 %>
                    <tr>
                        <td>Social Account</td>
                    <% @member.social_accounts.each do |sa| %>
                        <td><%= sa.social_type%></td>
                    <% end %>
                    </tr>
                  <% end %>
               </table>
            </div>
        </div>
        <div class="panel-footer" style="height: 50px;">          
             <%= link_to "Edit", com_nbos_core_edit_path, {class: "btn-sm btn btn-success pull-right"}%>
          </div>
      </div>
    </div>
  </div>
 <% end %> 

app/views/com/nbos/core/users/sign_up.html.erb
<% if (@login.present? && @login.message.present?) || flash[:notice] %>
    <%= render partial: "com/nbos/core/shared/alerts", locals: {obj: @login, notice: flash[:notice]} %>
<% end %>
<div class="container">    
    <div id="signupbox" style="margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
      <div class="panel panel-info">
        <div class="panel-heading">
          <div class="panel-title">Sign Up</div>
          <div style="float:right; font-size: 85%; position: relative; top:-10px;">
            <%#= link_to "Sign In", com_nbos_core_login_path, style: "color: #fff " %>
          </div>
        </div>
        <div class="panel-body">
          <%= form_for(@login, url: com_nbos_core_sign_up_path, method: 'post', html: { role: "form", id: "signupForm", class: "form-horizontal" }) do |f| %>
            <div class="form-group">
              <label for="usd" class="col-md-3 control-label">Username</label>
              <div class="col-md-9">
                 <%= f.text_field :username, autofocus: true, class: "form-control", id: "username", title: "Please enter your username", placeholder: "UserName", required: true  %>
                <%= errors_for @login, :username %>
              </div>
            </div>
            <div class="form-group">
              <label for="password" class="col-md-3 control-label">Password</label>

              <div class="col-md-9">
                <%= f.password_field :password, class: "form-control", id: "password", title: "Please enter password", placeholder: "******" , required: true%>
                <%= errors_for @login, :password %>
              </div>
            </div>
            <div class="form-group">
              <label for="email" class="col-md-3 control-label">Email</label>

              <div class="col-md-9">
                <%= f.email_field :email, class: "form-control", id: "email", title: "Please enter your email", placeholder: "example@gmail.com", required: true%>
                <%= errors_for @login, :email %>
              </div>
            </div>
            <div class="form-group">
              <label for="firstname" class="col-md-3 control-label">First Name</label>

              <div class="col-md-9">
               <%= f.text_field :firstName, class: "form-control", id: "firstName", title: "Please enter your first name", placeholder: "Jhon", required: true%>
                <%= errors_for @login, :firstName %>
              </div>
            </div>
            <div class="form-group">
              <label for="lastname" class="col-md-3 control-label">Last Name</label>

              <div class="col-md-9">
                <%= f.text_field :lastName, class: "form-control", id: "lastName", title: "Please enter your last name", placeholder: "Smith", required: true%>
                <%= errors_for @login, :lastName %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-md-offset-3 col-md-9">
               <%= f.submit  "Sign Up", class: "btn btn-success" %>
              </div>
            </div>
<!--             <div style="border-top: 1px solid #999; padding-top:20px" class="form-group">
              <div class="col-md-offset-3 col-md-9">
                <button id="btn-fbsignup" type="button" class="btn btn-primary">
                  <i class="icon-facebook"></i> Sign Up with Facebook
                </button>
              </div>
            </div> -->
          <% end %>
        </div>
      </div>
    </div>
  </div>