config/routes.rb
Rails.application.routes.draw do

    namespace :com, :path => nil do
      namespace :nbos, :path => nil do
        namespace :core, :path => nil do
           get "/" => "auth#login"
           match 'login' => "auth#login", as: 'login', via: [:get, :post]
           match 'sign_up' => "users#sign_up", as: 'sign_up', via: [:get, :post]
           get 'user_profile' => "users#show", as: 'user_profile'
           match 'users' => "users#edit", as: 'edit', via: [:get, :post]
           get 'dash_board' => "users#dash_board", as: 'dash_board'
           match 'change_password' => "auth#change_password", as: 'change_password', via: [:get, :post]
           match 'forgot_password' => "auth#forgot_password", as: 'forgot_password', via: [:get, :post]
           get 'logout' => "auth#logout", as: 'logout'
           get 'get_media' => "media#get_media", as: 'get_media'
           put 'update_media' => "media#update_media", as: 'update_media'
        end  
      end
    end

    namespace :com, :path => nil do
      namespace :nbos, :path => nil do
        namespace :social, :path => nil do
          get '/auth/:provider/callback' => "social#create"
        end  
      end
    end 
      
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!--<a class="navbar-brand" href="#">Ruby On Rails Client For Wavelabs Api</a>-->
            <% if current_user %>
              <%= link_to "Ruby On Rails Client For Wavelabs Api", com_nbos_core_dash_board_path , {class: "navbar-brand"}%>
            <% else %>
              <%= link_to "Ruby On Rails Client For Wavelabs Api", com_nbos_core_path , {class: "navbar-brand"}%>
            <% end %>  
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
                <li><%= link_to "Profile", com_nbos_core_user_profile_path(id: session[:member]["id"]) %></li>
                <li><%= link_to "Picture", com_nbos_core_get_media_path %></li>
                <% if !is_a_social_member? %>
                  <li><%= link_to "Change Password", com_nbos_core_change_password_path %></li>
                <% end %>  
                <li><%= link_to "Log Out", com_nbos_core_logout_path %></li>
              <% else %>
                <li><%= link_to "Sign Up", com_nbos_core_sign_up_path %></li>
                <li><%= link_to "Sign In", com_nbos_core_login_path %></li>
              <% end %>  
            </ul>
        </div>
    </div>
</header> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StarterAppRestRails</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render '/layouts/header' %>

<%= yield %>

</body>
</html>